import { Tajawal,  Barlow } from "next/font/google";
import "./globals.css";

const changa = Barlow({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

const tajawal = Tajawal({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700"],
});

export const metadata = {
  title: "Urban Build",
  description: "Generated by Mohammed Sobhi❤",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${tajawal.variable} ${changa.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
